# Generated by Django 6.0.2 on 2026-03-03 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=300, verbose_name="Адрес")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "map_url",
                    models.URLField(
                        blank=True,
                        help_text="Ссылка на Яндекс.Карты или Google Maps",
                        verbose_name="Ссылка на карту",
                    ),
                ),
                (
                    "work_hours",
                    models.CharField(
                        default="Пн-Пт: 9:00-20:00, Сб: 10:00-18:00, Вс: выходной",
                        max_length=200,
                        verbose_name="Режим работы",
                    ),
                ),
                ("vk_url", models.URLField(blank=True, verbose_name="ВКонтакте")),
                ("telegram_url", models.URLField(blank=True, verbose_name="Telegram")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Контактная информация",
                "verbose_name_plural": "Контактная информация",
            },
        ),
        migrations.CreateModel(
            name="FeedbackMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Для обратной связи",
                        max_length=20,
                        verbose_name="Телефон",
                    ),
                ),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата отправки"
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False,
                        help_text="Отмечено как обработанное",
                        verbose_name="Обработано",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата обработки"
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обработал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение обратной связи",
                "verbose_name_plural": "Сообщения обратной связи",
                "ordering": ["-created_at"],
            },
        ),
    ]
