# Generated by Django 6.0.2 on 2026-03-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutPageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="О компании",
                        max_length=200,
                        verbose_name="Заголовок страницы",
                    ),
                ),
                (
                    "history_title",
                    models.CharField(
                        default="Наша история",
                        max_length=200,
                        verbose_name="Заголовок раздела истории",
                    ),
                ),
                (
                    "history_text",
                    models.TextField(verbose_name="Текст истории компании"),
                ),
                (
                    "history_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="pages/about/",
                        verbose_name="Изображение к истории",
                    ),
                ),
                (
                    "mission_title",
                    models.CharField(
                        default="Наша миссия",
                        max_length=200,
                        verbose_name="Заголовок миссии",
                    ),
                ),
                ("mission_text", models.TextField(verbose_name="Текст миссии")),
                (
                    "values_title",
                    models.CharField(
                        default="Наши ценности",
                        max_length=200,
                        verbose_name="Заголовок ценностей",
                    ),
                ),
                (
                    "values",
                    models.JSONField(
                        default=list,
                        help_text='Список ценностей в формате [{"title": "...", "description": "..."}]',
                        verbose_name="Ценности",
                    ),
                ),
                (
                    "equipment_title",
                    models.CharField(
                        default="Наше оборудование",
                        max_length=200,
                        verbose_name="Заголовок раздела оборудования",
                    ),
                ),
                (
                    "equipment_description",
                    models.TextField(blank=True, verbose_name="Описание оборудования"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Meta Title"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Meta Description"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Контент страницы 'О компании'",
                "verbose_name_plural": "Контент страницы 'О компании'",
            },
        ),
        migrations.CreateModel(
            name="HomePageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Медицинский диагностический центр",
                        max_length=200,
                        verbose_name="Заголовок главного баннера",
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        default="Современное оборудование и опытные врачи",
                        max_length=500,
                        verbose_name="Подзаголовок",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="pages/home/",
                        verbose_name="Фоновое изображение",
                    ),
                ),
                (
                    "about_title",
                    models.CharField(
                        default="О нашем центре",
                        max_length=200,
                        verbose_name="Заголовок раздела 'О компании'",
                    ),
                ),
                (
                    "about_text",
                    models.TextField(
                        help_text="Краткое описание для главной страницы",
                        verbose_name="Текст о компании",
                    ),
                ),
                (
                    "about_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="pages/home/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "advantages",
                    models.JSONField(
                        default=list,
                        help_text='Список преимуществ в формате [{"title": "...", "description": "..."}]',
                        verbose_name="Преимущества",
                    ),
                ),
                (
                    "patients_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Для отображения статистики",
                        verbose_name="Количество пациентов",
                    ),
                ),
                (
                    "doctors_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество врачей"
                    ),
                ),
                (
                    "experience_years",
                    models.PositiveIntegerField(default=0, verbose_name="Лет на рынке"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Meta Title"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Meta Description"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Контент главной страницы",
                "verbose_name_plural": "Контент главной страницы",
            },
        ),
    ]
