# Generated by Django 6.0.2 on 2026-03-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Название услуги"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Уникальный идентификатор для URL, генерируется из названия",
                        max_length=250,
                        unique=True,
                        verbose_name="URL-идентификатор",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        help_text="Отображается в списке услуг",
                        max_length=300,
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "full_description",
                    models.TextField(
                        blank=True,
                        help_text="Детальное описание на странице услуги",
                        verbose_name="Полное описание",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Стоимость услуги в рублях",
                        max_digits=10,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Иллюстрация для услуги",
                        null=True,
                        upload_to="services/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Среднее время приема в минутах",
                        verbose_name="Длительность (минут)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Отображать ли услугу на сайте",
                        verbose_name="Активна",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Чем меньше число, тем выше в списке",
                        verbose_name="Порядок сортировки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="services_se_slug_4657d0_idx"),
                    models.Index(
                        fields=["is_active", "order"],
                        name="services_se_is_acti_dbc8d8_idx",
                    ),
                ],
            },
        ),
    ]
