# Generated by Django 6.0.2 on 2026-03-03 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosticResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result_file",
                    models.FileField(
                        help_text="PDF, изображения или архивы",
                        upload_to="results/%Y/%m/%d/",
                        verbose_name="Файл с результатами",
                    ),
                ),
                (
                    "doctor_comment",
                    models.TextField(blank=True, verbose_name="Заключение врача"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Результат диагностики",
                "verbose_name_plural": "Результаты диагностики",
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Дата приема")),
                ("time", models.TimeField(verbose_name="Время приема")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтвержден"),
                            ("completed", "Завершен"),
                            ("cancelled", "Отменен"),
                            ("no_show", "Не явился"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "patient_comment",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительная информация к записи",
                        verbose_name="Комментарий пациента",
                    ),
                ),
                (
                    "admin_comment",
                    models.TextField(
                        blank=True,
                        help_text="Внутренние заметки",
                        verbose_name="Комментарий администратора",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="doctors.doctor",
                        verbose_name="Врач",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="services.service",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись на прием",
                "verbose_name_plural": "Записи на прием",
                "ordering": ["-date", "-time"],
            },
        ),
    ]
