# Generated by Django 6.0.2 on 2026-03-03 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пациент",
            ),
        ),
        migrations.AddField(
            model_name="diagnosticresult",
            name="appointment",
            field=models.OneToOneField(
                limit_choices_to={"status": "completed"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnostic_result",
                to="appointments.appointment",
                verbose_name="Запись",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["date", "status"], name="appointment_date_32174a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["user", "-date"], name="appointment_user_id_4fc835_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("doctor", "date", "time")},
        ),
    ]
