# Generated by Django 6.0.2 on 2026-03-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="ФИО врача"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=250,
                        unique=True,
                        verbose_name="URL-идентификатор",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        help_text="Например: кардиолог, невролог",
                        max_length=100,
                        verbose_name="Специализация",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="doctors/", verbose_name="Фото"
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        help_text="Образование, опыт, достижения",
                        verbose_name="Биография",
                    ),
                ),
                (
                    "experience_years",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Стаж работы (лет)"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Отображать ли врача на сайте",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Какие услуги оказывает врач",
                        related_name="doctors",
                        to="services.service",
                        verbose_name="Услуги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Врач",
                "verbose_name_plural": "Врачи",
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="doctors_doc_slug_3caa7e_idx"),
                    models.Index(
                        fields=["specialty"], name="doctors_doc_special_4b2702_idx"
                    ),
                ],
            },
        ),
    ]
